DELETE FROM USER_;
INSERT INTO USER_ VALUES (1,'user1@gmail.com','user1');
INSERT INTO USER_ VALUES (2,'user2@gmail.com','user2');
INSERT INTO USER_ VALUES (3,'user3@gmail.com','user3');
INSERT INTO USER_ VALUES (4,'user4@gmail.com','user4');
INSERT INTO USER_ VALUES (5,'user5@gmail.com','user5');
INSERT INTO USER_ VALUES (6,'user6@gmail.com','user6');
INSERT INTO USER_ VALUES (7,'user7@gmail.com','user7');
INSERT INTO USER_ VALUES (8,'user8@gmail.com','user8');
INSERT INTO USER_ VALUES (9,'user9@gmail.com','user9');
INSERT INTO USER_ VALUES (10,'user10@gmail.com','user10');